# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grabber.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(589, 336)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(589, 336))
        MainWindow.setMaximumSize(QtCore.QSize(589, 336))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setEnabled(False)
        self.startButton.setGeometry(QtCore.QRect(390, 240, 191, 27))
        self.startButton.setObjectName("startButton")
        self.startURL = QtWidgets.QLineEdit(self.centralwidget)
        self.startURL.setGeometry(QtCore.QRect(10, 140, 371, 27))
        self.startURL.setObjectName("startURL")
        self.endURL = QtWidgets.QLineEdit(self.centralwidget)
        self.endURL.setGeometry(QtCore.QRect(10, 190, 371, 27))
        self.endURL.setObjectName("endURL")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 110, 121, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 170, 161, 19))
        self.label_2.setObjectName("label_2")
        self.rangeStart = QtWidgets.QSpinBox(self.centralwidget)
        self.rangeStart.setGeometry(QtCore.QRect(390, 30, 49, 28))
        self.rangeStart.setMaximum(5000)
        self.rangeStart.setObjectName("rangeStart")
        self.rangeEnd = QtWidgets.QSpinBox(self.centralwidget)
        self.rangeEnd.setGeometry(QtCore.QRect(390, 80, 49, 28))
        self.rangeEnd.setMaximum(5000)
        self.rangeEnd.setObjectName("rangeEnd")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(390, 10, 141, 19))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(390, 60, 161, 19))
        self.label_4.setObjectName("label_4")
        self.delay = QtWidgets.QSpinBox(self.centralwidget)
        self.delay.setGeometry(QtCore.QRect(390, 140, 49, 28))
        self.delay.setMinimum(1)
        self.delay.setMaximum(60)
        self.delay.setProperty("value", 2)
        self.delay.setObjectName("delay")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(390, 120, 161, 19))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 60, 121, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 121, 21))
        self.label_8.setObjectName("label_8")
        self.login = QtWidgets.QLineEdit(self.centralwidget)
        self.login.setGeometry(QtCore.QRect(10, 30, 171, 27))
        self.login.setObjectName("login")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(10, 80, 171, 27))
        self.password.setObjectName("password")
        self.loginButton = QtWidgets.QPushButton(self.centralwidget)
        self.loginButton.setGeometry(QtCore.QRect(390, 190, 191, 27))
        self.loginButton.setObjectName("loginButton")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 220, 321, 19))
        self.label_9.setObjectName("label_9")
        self.destDir = QtWidgets.QLineEdit(self.centralwidget)
        self.destDir.setGeometry(QtCore.QRect(10, 240, 371, 27))
        self.destDir.setText("")
        self.destDir.setObjectName("destDir")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 270, 571, 21))
        self.label_10.setObjectName("label_10")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 589, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LitresGrabber"))
        self.startButton.setText(_translate("MainWindow", "Начать граббинг"))
        self.startURL.setPlaceholderText(_translate("MainWindow", "Начальный URL"))
        self.endURL.setPlaceholderText(_translate("MainWindow", "Конечный URL"))
        self.label.setText(_translate("MainWindow", "Начальный URL:"))
        self.label_2.setText(_translate("MainWindow", "Конечный URL:"))
        self.label_3.setText(_translate("MainWindow", "Первая страница:"))
        self.label_4.setText(_translate("MainWindow", "Последняя страница:"))
        self.label_5.setText(_translate("MainWindow", "Задержка (сек):"))
        self.label_7.setText(_translate("MainWindow", "Пароль:"))
        self.label_8.setText(_translate("MainWindow", "Логин:"))
        self.login.setPlaceholderText(_translate("MainWindow", "Логин"))
        self.password.setPlaceholderText(_translate("MainWindow", "Пароль"))
        self.loginButton.setText(_translate("MainWindow", "Войти"))
        self.label_9.setText(_translate("MainWindow", "Директория сохранения изображений:"))
        self.destDir.setPlaceholderText(_translate("MainWindow", "Директория сохранения"))
        self.label_10.setText(_translate("MainWindow", "Владислав Калугин, 2019"))
